version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: empresaeco
    volumes:
      - .:/usr/src/app
    command: npm start

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empresaeco
    volumes:
      - ./db/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    ports:
      - "3306:3306"
